bai7/Models/ErrorViewModel.cs
using System;

namespace bai7.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

bai7/Models/PersonModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace bai7.Models
{
    public class PersonModel
    {
        public PersonModel( string firstName, string lastName, string gender, DateTime dob, int phoneNumber, string birthPlace, int age, string isGraduated, string email)
        {
            
            FirstName = firstName;
            LastName = lastName;
            Gender = gender;
            Dob = dob;
            PhoneNumber = phoneNumber;
            BirthPlace = birthPlace;
            Age = age;
            IsGraduated = isGraduated;
            Email = email;
        }

        public PersonModel(){

        }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public DateTime Dob { get; set; }
        // [StringLength(9)]
        [RegularExpression("^\\d{9,}$")]
        [Required]
        public int PhoneNumber { get; set; }
        public string BirthPlace { get; set; }
        public int Age { get; set; }
        public string IsGraduated { get; set; }
        [EmailAddress]
        [Required]
        public string Email{get;set;}


    }
}

bai7/Models/Service.cs
using System;
using System.Collections.Generic;
using System.Linq;


namespace bai7.Models
{
    public class Service
    {
        public List<PersonModel> persons { get; set; }
        public Service(){

          persons = new List<PersonModel>(
             // new PersonModel{FirstName="hieu1",LastName="hoang1",Dob= new DateTime (2000,08,09),Gender="nam",PhoneNumber=123456789,BirthPlace="HN",Age=10,IsGraduated="yes",Email="hieu@gmai.com"}
          ); 
        }

        // public static List<PersonModel> Persons { get; set; }

        public PersonModel[] Get() => persons.ToArray();
        public PersonModel Get(int phoneNumber) => persons.SingleOrDefault(x => x.PhoneNumber == phoneNumber);

        public void Add(PersonModel person) => persons.Add(person);
        public void Edit(PersonModel person)
        {
            var b = Get(person.PhoneNumber);
            persons.Remove(b);
            persons.Add(person);
        }
        public void Delete(int phoneNumber)
        {
            var b = Get(phoneNumber);
            persons.Remove(b);
        }
    }
}

bai7/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using bai7.Models;

namespace bai7.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

bai7/Controllers/RookiesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using bai7.Models;
using Microsoft.AspNetCore.Http;

namespace bai7.Controllers
{
    public class RookiesController : Controller
    {
        // static List<PersonModel> persons = new List<PersonModel>();
        private readonly Service _service;
        public RookiesController(Service service)
        {
            _service = service;
        }

        public IActionResult Index()
        {

            return View(_service.Get());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstName,LastName,Gender,Dob,PhoneNumber,Email")] PersonModel person)
        {

            if (ModelState.IsValid)
            {
                _service.Add(person);
                return RedirectToAction(nameof(Index));
            }

            return View(person);
        }


        public IActionResult Edit(int phoneNumber)
        {
            var a = _service.Get(phoneNumber);
            return View(a);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("FirstName,LastName,Gender,Dob,PhoneNumber,Email")] PersonModel person)
        {

            var a = _service.Get(person.PhoneNumber);
            if (a != null)
            {
                _service.Edit(person);
                return RedirectToAction("Index");
            }

            return View(a);
        }


        public IActionResult Delete(PersonModel person)
        {
            var a = _service.Get(person.PhoneNumber);
            if (a != null)
            {
                _service.Delete(person.PhoneNumber);
                
                return RedirectToAction("Index");
            }

            return View(a);

        }
        public IActionResult Detail(int phoneNumber)
        {
            var a = _service.Get(phoneNumber);
            return View(a);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Detail([Bind("FirstName,LastName,Gender,Dob,PhoneNumber,Email")] PersonModel person)
        {

            var a = _service.Get(person.PhoneNumber);
            if (a != null)
            {
                _service.Delete(person.PhoneNumber);
                var b = this.HttpContext.Session.GetString("person");
                HttpContext.Session.SetString("person", $"{person.LastName}");
                TempData["personDelete"] = $"Person {person.LastName} was removed from the list successfully! ";
                return RedirectToAction("Index");
                
            }

            return View(a);
        }


    }
}

bai7/Views/Rookies/Create.cshtml
@model bai7.Models.PersonModel
<form asp-action="Create" >
    <div class="form-group">
        <label for="exampleInputEmail1">First Name</label>
        <input type="text" class="form-control" asp-for="FirstName">
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Last Name</label>
        <input type="text" class="form-control" asp-for="LastName">
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Gender" for="">Gender</label>
        <select class="form-control" id="" asp-for="Gender">
            <option value="Nữ" asp-for="Gender">Nữ</option>
            <option value="Nam" asp-for="Gender">Nam</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Date of Birth</label>
        <input type="date" class="form-control" asp-for="Dob">
        <span asp-validation-for="Dob" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Phone Number</label>
        <input type="number" class="form-control" asp-for="PhoneNumber">
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" asp-for="Email">
    <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" value="Create" class="btn btn-primary">Submit</button>
    </div>
</form>

bai7/Views/Rookies/Delete.cshtml
<script language="javascript" type="text/javascript">
function fnConfirmDelete() {
  return confirm("Are you sure you want to delete this?");
}
</script>

bai7/Views/Rookies/Detail.cshtml
@model bai7.Models.PersonModel;

<form asp-controller="Rookies" asp-action="Detail" >
    <div>   
        @Html.LabelFor(x=>x.FirstName)
        @Html.DisplayFor(x=>x.FirstName)
    </div>
    <div>
        @Html.LabelFor(x=>x.LastName)
        @Html.DisplayFor(x=>x.LastName)
    </div>
    <div>
        @Html.LabelFor(x=>x.Gender)
        @Html.DisplayFor(x=>x.Gender)</div>
    <div>
        @Html.LabelFor(x=>x.Dob)
        @Html.DisplayFor(x=>x.Dob)
    </div>
    <div>
        @Html.LabelFor(x=>x.PhoneNumber)
        @Html.DisplayFor(x=>x.PhoneNumber)
    </div>
    <div>
        @Html.LabelFor(x=>x.Email)
        @Html.DisplayFor(x=>x.Email)
    </div>
    <br/>
    
    <input type="submit" value="Delete" asp-route-phoneNumber="@Model.PhoneNumber" />
    
    
    
    
</form>

bai7/Views/Rookies/Edit.cshtml
@model bai7.Models.PersonModel;

<form asp-controller="Rookies" asp-action="Edit" >
    <div>   
        @Html.LabelFor(x=>x.FirstName)
        @Html.EditorFor(x=>x.FirstName)
    </div>
    <div>
        @Html.LabelFor(x=>x.LastName)
        @Html.EditorFor(x=>x.LastName)
    </div>
    <div>
        @Html.LabelFor(x=>x.Gender)
        @Html.EditorFor(x=>x.Gender)</div>
    <div>
        @Html.LabelFor(x=>x.Dob)
        @Html.EditorFor(x=>x.Dob)
    </div>
    <div>
        @Html.LabelFor(x=>x.PhoneNumber)
        @Html.EditorFor(x=>x.PhoneNumber)
    </div>
    <div>
        @Html.LabelFor(x=>x.Email)
        @Html.EditorFor(x=>x.Email)
    </div>
    <br/>
    <input type="submit" value="Edit" />
    
    
    
    
</form>

bai7/Views/Rookies/Index.cshtml
@using Microsoft.AspNetCore.Http    
@* @inject IHttpContextAccessor httpContextAccessor    *@
@model IEnumerable<bai7.Models.PersonModel>

@* @model List<PersonModel> *@



<table>
    <tr>
        <a asp-controller="Rookies" asp-action="Create">Create</a>
    </tr>
    <tr>
        
        <th>First Name</th>
        <th>Last Name</th>
        <th>Gender</th>
        <th>Date Of Birth</th>
        <th>Phone Number</th>
        <th>Email</th>
        
    </tr>
    @{
        foreach(var i in Model){
        <tr>
        <td>@i.FirstName</td>
        <td>@i.LastName</td>
        <td>@i.Gender</td>
        <td>@i.Dob</td>
        <td>@i.PhoneNumber</td>
        <td>@i.Email</td>
        <td>@Html.ActionLink("Edit", "Edit", new { phoneNumber = i.PhoneNumber })</td>
        <td>@Html.ActionLink("Delete", "Delete",new { phoneNumber = i.PhoneNumber },new { onclick = "return confirm('Are you sure you wish to delete this?');" })</td>
        <td>@Html.ActionLink("Detail", "Detail", new { phoneNumber = i.PhoneNumber })</td>
        </tr>
        }
        
    }
    
</table>

bai7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bai7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bai7</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rookies" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - bai7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>